import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { PrismaClient } from '@prisma/client';
const app=express(); const prisma=new PrismaClient();
const PORT=process.env.PORT||8080; const ORIGIN=process.env.ORIGIN||'http://localhost:5173';
app.use(cors({origin:ORIGIN,credentials:true})); app.use(express.json());
app.get('/health',(req,res)=>res.json({ok:true}));
app.get('/categories',async(req,res)=>{const categories=await prisma.category.findMany({orderBy:{name:'asc'}});res.json(categories)});
app.get('/brands',async(req,res)=>{const brands=await prisma.brand.findMany({orderBy:{name:'asc'}});res.json(brands)});
app.get('/products',async(req,res)=>{const {category,brand,q,promo,order='price_asc',page='1',pageSize='20'}=req.query;const where={}; if(category) where.category={slug:category}; if(brand) where.brand={slug:brand}; if(promo==='true') where.promo=true; if(q) where.name={contains:q,mode:'insensitive'}; const [field,dir]=order.split('_'); const orderBy={}; if(['price','name','stock'].includes(field)) orderBy[field]=(dir==='desc'?'desc':'asc'); else orderBy['price']='asc'; const take=Math.min(Math.max(parseInt(pageSize,10)||20,1),100); const skip=(Math.max(parseInt(page,10)||1,1)-1)*take; const [total,items]=await Promise.all([prisma.product.count({where}),prisma.product.findMany({where,orderBy,skip,take,include:{category:true,brand:true}})]); res.json({total,page:Number(page),pageSize:take,items:items.map(p=>({id:p.id,name:p.name,price:Number(p.price),spec:p.spec,imageUrl:p.imageUrl,promo:p.promo,stock:p.stock,category:{slug:p.category.slug,name:p.category.name},brand:{slug:p.brand.slug,name:p.brand.name}}))});});
app.get('/shipping/quote',(req,res)=>{const {cep,weightKg='1.2'}=req.query;const clean=String(cep||'').replace(/\D/g,''); if(clean.length!==8) return res.status(400).json({error:'CEP inválido. Use 8 dígitos.'}); const first=parseInt(clean[0],10); const base=12.90; const regionFactor=[1.0,1.0,1.05,1.10,1.15,1.20,1.25,1.30,1.35,1.40][first]||1.25; const perKg=3.50; const eta=Math.max(2,Math.round(2+(first*0.6))); const price=+(base*regionFactor+Number(weightKg)*perKg).toFixed(2); res.json({price,eta});});
app.listen(PORT,()=>console.log(`API http://localhost:${PORT}`));
